### PR TITLE
A bunch of fixes so that site.py works

### PR DESCRIPTION
**Pull request by isaiah**
This is the all in one PR that includes changes in all previous PRs, if it doesn't make sense, I'll split them into small pieces and create pull requests separately.

With this branch, one can run `dist/bin/jython` without the `-S` option.

### CODE REVIEW

**Comment by fwierzbicki** [comment]
Hi @isaiah this one is indeed a little too big to review at once. I have already merged two of the smaller pull requests, and I am working on a third. After I get done with all of the other pull requests, I'll see what's left of this one (assuming that there is more to this one than just the sum of the small ones). It might be manageable after that. I'll let you know!

**Comment by fwierzbicki** [comment]
Hi Isaiah, sorry I have neglected looking at these for so long. I just merged the third of the smaller patches. The others have conflicts, and I have time again to evaluate. This patch is a bit too big for me, if you could break it up into smaller ones I'll be able to get through it quicker. I will try to be more on top of these - it is great work!

**Comment by isaiah** [comment]
@fwierzbicki Thanks for reviewing, I would like to see my changes in the main repository so someone else interested can have a better start point, there are simply too much work to do :)

I've fixed `PEP-3135` `super()` without parameter,  `PEP-380` sub-generators and `PEP-3134` exception chaining, the main features that blocked proper execution of the specs, currently it can run and report errors/failure when run a certain spec.

**Comment by fwierzbicki** [comment]
Isalah, I would like to see this in the main repo too :) -- how about this, if you can get the conflicts resolved for this large pull request, I'll do my best to review it this week (probably over the weekend) and try to get it in as it is. I understand that it would be a lot of work to break it up. The fact that it can run Jython without the -S is a great step forward.

**Comment by isaiah** [comment]
@fwierzbicki That sounds great, I'll fix the conflicts. The change set is too big to be reviewed on github, that's probably because I introduced the `3.5.1` stdlib, you can focus on the `src` folder to get less noise.

**Comment by fwierzbicki** [comment]
Hi Isaiah,
I merged the site.py branch, but then ran into some trouble. The grammar didn't work until I did the following:

```
 //raise_stmt: 'raise' [test ['from' test]]
 raise_stmt
-    ;
-
-raise_stmt
 @init {
     stmt stype = null;
 }
@@ -2623,7 +2620,7 @@ NAME:    ( 'a' .. 'z' | 'A' .. 'Z' | '_')
         ( 'a' .. 'z' | 'A' .. 'Z' | '_' | '0' .. '9' )*
     ;
 
-NAME_CONSTANT: 'None' | 'True' | 'False' ;
+//NAME_CONSTANT: 'None' | 'True' | 'False' ;
```
And FilenoUtil is missing an import of ChannelFD, there may be other issues - I can't compile with the ChannelFD issue.

**Pull request merged**
